apiVersion: v1
kind: Service
metadata:
  name: llm-consumer-description-service
spec:
  selector:
    app: llm-consumer-description-pod
  ports:
    - protocol: TCP
      port: 8042   
      targetPort: 8042  
  type: ClusterIP 
