export type {
    OccurrenceStatsResponse,
    OccurrenceListResponse,
    OccurrenceResponse,
    NotResolvedOccurrencesResponse,
    LoginCredentials,
    LoginResponse,
    SignupCredentials,
    UserProfile,
    PreSubmitOccurrenceResponse,
    SubmitOccurrence,
    ConfirmationCode,
    OccurrenceSuggestionsResponse,
    LocationCoords,
    NewPasswordRequest,
    LLMResponse,
} from './dto/dto';

export {
    logInAPI,
    signUpAPI,
    putUserProfile,
    getUserOccurrenceDetails,
    getUserOccurrences,
    getOccurrence,
    getNotResolvedOccurrences,
    deleteUserAccount,
    getUserDetails,
    preSubmitOccurrence,
    submitOccurrence,
    confirmCode,
    confirmCodeUpdate,
    getEmailNotifications,
    getOccurrenceSuggestions,
    getPhoto,
    putEmailNotifications,
    refreshToken,
    resendCode,
    forgottenPassword,
    confirmNewPassword,
    connectIncidentWebSocket,
} from './api-consumer';
  
    