apiVersion: v1
kind: Service
metadata:
  name: database-cassandra-headless
spec:
  clusterIP: None
  selector:
    app: database-cassandra-pod
  ports:
    - protocol: TCP
      port: 9042
      targetPort: 9042