apiVersion: v1
kind: Service
metadata:
  name: database-cassandra
spec:
  selector:
    app: database-cassandra-pod
  ports:
    - protocol: TCP
      port: 9042   
      targetPort: 9042  
  type: ClusterIP 
