## External imports
import os
from dotenv import load_dotenv

# ======================== CONFIG ========================
load_dotenv()

## LLM
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
DESCRIPTION_CATEGORY_SEVERITY_SYS_INSTRUCTION = os.getenv("DESCRIPTION_CATEGORY_SEVERITY_SYS_INSTRUCTION")
MERGE_DESCRIPTION_CATEGORY_SEVERITY_SYS_INSTRUCTION = os.getenv("MERGE_DESCRIPTION_CATEGORY_SEVERITY_SYS_INSTRUCTION")
INCIDENT_DESCRIPTION_SIMILARITY_INSTRUCTION = os.getenv("INCIDENT_DESCRIPTION_SIMILARITY_INSTRUCTION")
INCIDENT_DESCRIPTION_SIMILARITY_THRESHOLD = os.getenv("INCIDENT_DESCRIPTION_SIMILARITY_THRESHOLD")
LLM_BOOTSTRAP_SERVERS = os.getenv("LLM_BOOTSTRAP_SERVERS")
TOPIC_NAME = os.getenv("TOPIC_NAME")
DESCRIPTION_CATEGORY_SEVERITY_TOPIC = os.getenv("DESCRIPTION_CATEGORY_SEVERITY_TOPIC")
CHECK_INCIDENT_RESOLVED_TOPIC = os.getenv("CHECK_INCIDENT_RESOLVED_TOPIC")
CHECK_INCIDENT_RESOLVED_FROM_VIDEO_SYS_INSTRUCTION = os.getenv("CHECK_INCIDENT_RESOLVED_FROM_VIDEO_SYS_INSTRUCTION")
JOB_CLUSTERING_TOPIC = os.getenv("JOB_CLUSTERING_TOPIC")
LLM_GROUP_ID = os.getenv("LLM_GROUP_ID")
LLM_GROUP_INSTANCE_ID = os.getenv("LLM_GROUP_INSTANCE_ID")
DEFAULT_CATEGORY = os.getenv("DEFAULT_CATEGORY")
DEFAULT_SEVERITY = os.getenv("DEFAULT_SEVERITY")

## Cassandra Database
CASSANDRA_NODES = [os.getenv('CASSANDRA_HOST')] # We may have a list of nodes
CASSANDRA_PORT = os.getenv('CASSANDRA_PORT')
CASSANDRA_KEYSPACES = [os.getenv('AUTH_KEYSPACE'), os.getenv('H3_INDEX_KEYSPACE'), os.getenv('APP_DATA_KEYSPACE')]

## Keyspaces 
AUTH_KEYSPACE = os.getenv('AUTH_KEYSPACE')
APP_DATA_KEYSPACE = os.getenv('APP_DATA_KEYSPACE')
H3_INDEX_KEYSPACE = os.getenv("H3_INDEX_KEYSPACE")

## Minio Database
MINIO_ROOT_USER = os.getenv('MINIO_ROOT_USER')
MINIO_ROOT_PASSWORD = os.getenv('MINIO_ROOT_PASSWORD')
MINIO_HOST = os.getenv('MINIO_HOST')
MINIO_PORT = int(os.getenv('MINIO_PORT'))
MINIO_BUCKETS = [os.getenv('PHOTOS_BUCKET_NAME'), os.getenv('VIDEOS_BUCKET_NAME')]

## Bucket
PHOTOS_BUCKET_NAME = os.getenv('PHOTOS_BUCKET_NAME')
VIDEOS_BUCKET_NAME = os.getenv('VIDEOS_BUCKET_NAME')
