apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-consumer-check-resolved-incidents-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-consumer-check-resolved-incidents-pod
  template:
    metadata:
      labels:
        app: llm-consumer-check-resolved-incidents-pod
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: llm-consumer-check-resolved-incidents
          image: ghcr.io/pi-2024-2025-nap/backend-consumer-services:bc19fdef1493126c8e42118dcba9ec956b983fc3
          imagePullPolicy: IfNotPresent 
          ports:
            - containerPort: 8044
          env:
            - name: TOPIC_NAME
              value: "ai_check_incident_resolved"
            - name: LLM_GROUP_INSTANCE_ID
              value: "ai_worker_check_incident"
          envFrom:
            - configMapRef:
                name: app-config
