apiVersion: v1
kind: Service
metadata:
  name: llm-consumer-check-resolved-incidents-service
spec:
  selector:
    app: llm-consumer-check-resolved-incidents-pod
  ports:
    - protocol: TCP
      port: 8044   
      targetPort: 8044  
  type: ClusterIP 
