apiVersion: v1
kind: Service
metadata:
  name: llm-consumer-clustering-service
spec:
  selector:
    app: llm-consumer-clustering-pod
  ports:
    - protocol: TCP
      port: 8043   
      targetPort: 8043  
  type: ClusterIP 
