name: Build and Push Docker Images

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    strategy:
      matrix:
        service:
          - name: api-services
            context: ./api-services
          - name: cassandra
            context: ./database/cassandra
          - name: minio
            context: ./database/minio
          - name: consumer-services
            context: ./consumer-services

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push ${{ matrix.service.name }}
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.service.context }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/pi-2024-2025-nap/backend-${{ matrix.service.name }}:latest
            ${{ env.REGISTRY }}/pi-2024-2025-nap/backend-${{ matrix.service.name }}:${{ github.sha }}