apiVersion: v1
kind: Service
metadata:
  name: database-minio
spec:
  selector:
    app: database-minio-pod
  ports:
    - protocol: TCP
      port: 9000   
      targetPort: 9000  
  type: ClusterIP 
